services:
  web:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template
    working_dir: /var/www
    links:
      - php
    ports:
      - 8080:80
  php:
    build: .
    volumes:
      - .:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_ARBITRARY: 1

networks:
  default:
    name: library-net

